---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/Client/jSpamBot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/Client/TeamTalkAndroid"
    schedule:
      interval: "daily"
  - package-ecosystem: "swift"
    directory: "/Client/iTeamTalk/iTeamTalk"
    schedule:
      interval: "daily"
  - package-ecosystem: "swift"
    directory: "/Client/iTeamTalk/iTeamTalkTest"
    schedule:
      interval: "daily"
