version: 2
updates:
  - package-ecosystem: cargo
    directory: /Client/ttserverlog_rust
    schedule:
      interval: daily
      time: "00:00"
    groups:
      ttserverlog_rust:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /Library/teamtalk_rust
    schedule:
      interval: daily
      time: "00:00"
    groups:
      teamtalk_rust:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /Client/TeamTalkAndroid
    schedule:
      interval: daily
      time: "00:00"
    groups:
      TeamTalkAndroid:
        patterns:
          - "*"
