name: Bug Report
description: Submit a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is, and why you consider it to be a bug.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Application
      description: Which software is affected by the bug
      options:
        - label: qtTeamTalk
        - label: TeamTalkAndroid
        - label: iTeamTalk
        - label: TeamTalkClassic
        - label: TeamTalkServer
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Platform
      description: Which platform/OS is affected by the bug
      options:
        - label: Windows
        - label: macOS
        - label: Android
        - label: iOS
        - label: Linux
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
  - type: textarea
    attributes:
      label: Actual behavior
      description: A description of what is actually happening.
  - type: textarea
    attributes:
      label: Steps to reproduce problem
      placeholder: |
        A description with steps to reproduce the issue.
        1. Step 1
        2. Step 2
    validations:
      required: true
