name: Feature Request
description: Submit a feature request
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: A description of the feature you would like to see
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Application
      options:
        - label: TeamTalk for Desktop
        - label: TeamTalk for Android
        - label: TeamTalk for iOS
        - label: TeamTalk Server
    validations:
      required: true
