//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TeamTalk.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define USER_TIMEOUT                    60
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDS_WIZCAPTION                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_DISCONNECT                  104
#define IDS_CHANNEL_JOINED              105
#define IDS_CHANNEL_LEFT                106
#define IDS_CONNECT                     107
#define IDS_CREATECHANNEL               108
#define IDS_UPDATECHANNEL               109
#define IDS_CREATENEWCHANNEL            110
#define IDS_UPDEXISTINGCHANNEL          111
#define IDS_YES                         112
#define IDS_NO                          113
#define IDS_TALKING                     114
#define IDS_MUTE                        115
#define IDS_STREAMING_MEDIAFILE         116
#define IDS_DESKTOP                     117
#define IDS_VIDEOCAPTURE                118
#define IDS_MUTE_MEDIAFILE              119
#define IDS_PASSWORD_PROTECTED          120
#define IDS_CHANNEL_SELF_JOINED         121
#define IDS_SUPPORTS3D                  122
#define IDS_NOSUPPORTS3D                123
#define IDS_TESTSELECTED                124
#define IDS_STOP                        125
#define IDS_DEFAULT                     126
#define IDS_CHANNEL_SELF_LEFT           127
#define IDS_PREFERENCES                 128
#define IDS_IDHELP                      129
#define IDS_NEWNICKNAME                 130
#define IDS_CHANGENICKNAME              131
#define IDS_CLASSROOMCHANNEL            132
#define IDS_CLASSROOM_SELF_JOINED       133
#define IDS_FILES                       134
#define IDS_CHAT                        135
#define IDS_CLIENTSETTINGS              136
#define IDS_USER                        137
#define IDS_DESKTOPINPUT_REQUEST        138
#define IDS_DESKTOPINPUT_RETRACT        139
#define IDD_DIALOG_SERVERPROPERTIES     140
#define IDD_DIALOG_USERACCOUNTS         141
#define IDS_CHANNEL                     142
#define IDS_VOICELEVEL                  143
#define IDD_DIALOG_MOVETOCHANNEL        144
#define IDD_DIALOG_SERVERSTATISTICS     145
#define IDD_DIALOG_ONLINEUSERS          146
#define IDD_DIALOG_STORECONVERSATIONS   147
#define IDD_PROPPAGE_VIDEOCAPTURE       148
#define IDD_DIALOG_USERDESKTOP          149
#define IDD_DIALOG_DESKTOPSHARE         150
#define IDD_DIALOG_STREAMMEDIA          151
#define IDS_RESETPREFERENCES            152
#define IDS_RESTARTAPPLICATION          153
#define IDS_PUSHTOTALK                  154
#define IDD_DIALOG_GENERATETTFILE       155
#define IDS_MASTERVOL                   156
#define IDS_MICGAIN                     157
#define IDS_VOICEACTLEVEL               158
#define IDS_CHANTEXTMSG                 159
#define IDS_USERTEXTMSG                 160
#define IDD_PROPPAGE_TEXTTOSPEECHPAGE   161
#define IDS_BCASTTEXTMSG                162
#define IDS_USERLOGIN                   163
#define IDS_USERLOGOUT                  164
#define IDS_PROPPAGE_USEREVENTS         165
#define IDS_PROPPAGE_USERLOGIN          166
#define IDS_PROPPAGE_USERLOGOUT         167
#define IDS_PROPPAGE_USERJOINED         168
#define IDS_PROPPAGE_USERLEFT           169
#define IDS_PROPPAGE_TXTMSG_PRIV        170
#define IDS_PROPPAGE_TXTMSG_CHAN        171
#define IDS_PROPPAGE_TXTMSG_BCAST       172
#define IDS_PROPPAGE_SUB_CHANGE         173
#define IDS_PROPPAGE_SUB_TXTMSG_PRIV    174
#define IDS_PROPPAGE_SUB_TXTMSG_CHAN    175
#define IDS_PROPPAGE_SUB_TXTMSG_BCAST   176
#define IDS_PROPPAGE_SUB_VOICE          177
#define IDS_PROPPAGE_SUB_VIDEO          178
#define IDS_PROPPAGE_SUB_DESKTOP        179
#define IDS_PROPPAGE_SUB_DESKTOPINPUT   180
#define IDS_PROPPAGE_SUB_MEDIAFILE      181
#define IDS_PROPPAGE_SUBINT_TXTMSG_PRIV 182
#define IDS_PROPPAGE_SUBINT_TXTMSG_CHAN 183
#define IDS_PROPPAGE_SUBINT_VOICE       184
#define IDS_PROPPAGE_SUBINT_VIDEO       185
#define IDS_PROPPAGE_SUBINT_DESKTOP     186
#define IDS_PROPPAGE_SUBINT_DESKTOPINPUT 187
#define IDS_PROPPAGE_SUBINT_MEDIAFILE   188
#define IDS_PROPPAGE_CLASSROOM_CHANGE   189
#define IDS_PROPPAGE_CLASSROOM_VOICE    190
#define IDS_PROPPAGE_CLASSROOM_VIDEO    191
#define IDS_PROPPAGE_CLASSROOM_DESKTOP  192
#define IDS_PROPPAGE_CLASSROOM_MEDIAFILE 193
#define IDS_SUB_TEXTMSG                 194
#define IDS_SUB_CHANTEXTMSG             195
#define IDS_SUB_BCASTTEXTMSG            196
#define IDS_SUB_VOICE                   197
#define IDS_SUB_VIDEO                   198
#define IDS_SUB_DESKTOP                 199
#define IDS_SUB_DESKTOPINPUT            200
#define IDD_DIALOG_MESSAGE              201
#define IDD_DIALOG_TEAMTALK             202
#define IDD_DIALOG_CHANNEL              203
#define IDD_DIALOG_INPUT                204
#define IDD_DIALOG_CHANGESTATUS         205
#define IDS_SUB_MEDIAFILE               206
#define IDS_SUBINT_TEXTMSG              207
#define ID_INDICATOR_STATS              208
#define IDD_DIALOG_ABOUTBOX             209
#define IDS_SUBINT_CHANTEXTMSG          210
#define IDS_SUBINT_VOICE                211
#define IDD_PROPPAGE_WINDOWPAGE         212
#define IDR_MAINFRAME                   213
#define IDR_MENU_MAIN                   214
#define IDD_PROPPAGE_GENERALPAGE        215
#define IDD_DIALOG_FILETRANSFER         216
#define IDR_ACCELERATOR1                217
#define IDB_BITMAP_SESSION2             218
#define IDB_BITMAP_LOGO                 219
#define IDD_PROPPAGE_ADVANCEDPAGE       220
#define IDD_PROPPAGE_CLIENTPAGE         221
#define IDB_BITMAP_SESSION              222
#define IDD_PROPPAGE_SOUNDEVENTSPAGE    223
#define IDD_PROPPAGE_SOUNDSYSPAGE       224
#define IDS_SUBINT_VIDEO                226
#define IDD_DIALOG_USERINFO             227
#define IDB_BITMAP_MIKE                 228
#define IDB_BITMAP_VOICEACT             229
#define IDB_BITMAP_VOLUME               230
#define IDD_DIALOG_USERVOLUME           231
#define IDR_MENU_TRAY                   232
#define IDS_SUBINT_DESKTOP              234
#define IDD_WIZARD_GENERALPAGE          235
#define IDR_ACCELERATOR2                236
#define IDR_TOOLBAR1                    237
#define IDD_WIZARD_WELCOMEPAGE          238
#define IDD_WIZARD_SOUNDSYSPAGE         239
#define IDB_BITMAP_NOVOICEACT           240
#define IDB_BITMAP_NOVOLUME             241
#define IDB_BITMAP_TOOLBAR              242
#define IDD_DIALOG_HOSTMANAGER          243
#define IDS_SUBINT_MEDIAFILE            244
#define IDS_DESKTOPINPUT_GRANTED        245
#define IDD_WIZARD_COMPLETIONPAGE       246
#define IDS_DESKTOPINPUT_ACTIVE         248
#define IDD_DIALOG_KEYCOMP              249
#define IDR_MENU_MSGPOPUP               250
#define IDD_DIALOG_POSITION_USERS       251
#define IDD_TAB_CHAT                    252
#define IDD_TAB_FILES                   253
#define IDD_PROPPAGE_SHORTCUTS          254
#define IDD_DIALOG_USERVIDEO            255
#define IDD_DIALOG_BANNEDDLG            256
#define IDR_MENU_ONLINEUSERS            257
#define IDR_ACCELERATOR3                258
#define IDR_MENU_DESKTOPINPUT           259
#define IDS_DESKTOPINPUT_STOPPED        260
#define IDS_PROPPAGE_USERJOINED_SAME    261
#define IDS_PROPPAGE_USERLEFT_SAME      262
#define IDS_MAX_TX_USERS                263
#define IDS_USERJOINEDCHANNEL           264
#define IDS_USERLEFTCHANNEL             265
#define IDS_ROOTCHANNEL                 266
#define IDS_NOSOUNDDEVICE               267
#define IDS_USER_JOIN                   268
#define IDS_USER_LEFT                   269
#define IDS_USER_TEXTMSG                270
#define IDS_USER_CHANMSG                271
#define IDS_USER_QUESTIONMODE           272
#define IDS_USER_DESKACCESS_REQ         273
#define IDS_USER_NEWVIDEOSESSION        274
#define IDS_USER_NEWDESKTOPSESSION      275
#define IDS_CONNECTION_SERVERLOST       276
#define IDS_HOTKEY                      277
#define IDS_FILES_UPDATED               278
#define IDS_TRANSFER_COMPLETE           279
#define IDS_CHANNELSILENT               280
#define IDS_VOICEACTIVATED              281
#define IDS_VOICEDEACTIVATED            282
#define IDS_TXQUEUEHEAD                 283
#define IDS_TXQUEUESTOP                 284
#define IDS_ENABLEVOX                   285
#define IDS_DISABLEVOX                  286
#define IDS_ME_ENABLEVOX                287
#define IDS_ME_DISABLEVOX               288
#define IDD_TAB_CHANNELOP               289
#define IDD_TAB_CODECLIMIT              290
#define IDD_TAB_ABUSE                   291
#define IDS_DISABLED                    292
#define IDS_CMD10IN10                   293
#define IDS_CMD10IN60                   294
#define IDS_CMD60IN60                   295
#define IDS_CMDCUSTOM                   296
#define IDS_CMDLIMIT                    297
#define IDS_CMDNO                       298
#define IDS_CMDTIMEFRAME                299
#define IDS_ANONYMOUS                   300
#define IDD_DIALOG_WEBLOGIN             301
#define IDD_DIALOG_BANTYPE              302
#define IDS_NEWPROFILE                  303
#define IDS_DELETEPROFILE               304
#define IDS_SELECTPROFILE               305
#define IDS_PROFILENAME                 306
#define IDS_ASCENDING                   307
#define IDS_POPULATED                   308
#define IDS_EVERYONE                    309
#define IDS_FILEADDED                   310
#define IDS_FILEREMOVED                 311
#define IDS_FILEEVENTS                  312
#define IDS_FILEADD                     313
#define IDS_FILERM                      314
#define IDS_RESET                       315
#define IDD_DIALOG_BEARWARELOGIN        316
#define IDS_BEARWAREAUTHFAIL            317
#define IDS_BEARWARETIMEOUT             318
#define IDS_BEARWAREAUTHSUCCESS         319
#define IDS_USER_BCASTMSG               320
#define IDS_SNDINITFAILED               321
#define IDS_CONNECTING                  322
#define IDS_PLAY                        323
#define IDD_DIALOG_TTAUDIOPREPROCESSOR  324
#define IDD_DIALOG_SPEEXDSP             325
#define IDS_NOPREPROCESSOR              326
#define IDS_CONLOGIN                    327
#define IDS_CONFAILED                   329
#define IDS_ERROROCCURREDCOMMAND        330
#define IDS_CONNFAILED                  331
#define IDS_CONLOST                     332
#define IDS_CONSUCCESS                  333
#define IDS_LOGOUTSUCCESS               334
#define IDS_KICKEDFROMCHANNEL           335
#define IDS_UNKNOWNERROR                336
#define IDS_NOLONGERTRANSMIT            337
#define IDS_CANNOWTRANSMIT              338
#define IDS_NOLONGERTRANSMITVIDEO       339
#define IDS_CANNOWTRANSMITVIDEO         340
#define IDS_NOLONGERTRANSMITDESKTOP     341
#define IDS_CANNOWTRANSMITDESKTOP       342
#define IDS_NOLONGERTRANSMITMEDIAFILE   343
#define IDS_CANNOWTRANSMITMEDIAFILE     344
#define IDS_FAILEDTOWRITEAUDIOFILE      346
#define IDS_FAILEDTOSTARTFILETRANSFER   347
#define IDS_ERRORSTREAMINGTOCHANNEL     348
#define IDS_STREAMINGTOCHANNELSTART     349
#define IDS_STREAMINGTOCHANNELFINISH    350
#define IDS_STREAMINGTOCHANNELABORT     351
#define IDS_STREAMFAILEDBOX             352
#define IDS_ACCELERATORNOTLOADDED       353
#define IDS_UNABLELOADSETFILE           354
#define IDS_CREATENEWSETFILE            355
#define IDS_FAILEDTOCREATETRAYICON      356
#define IDS_FAILEDTOCOPY                357
#define IDS_RESETSETTINGS               358
#define IDS_DISCONNECTEDFROM            359
#define IDS_FAILEDTOINITIALIZENEWSD     360
#define IDS_RESTARTSS                   361
#define IDS_CHANGENN                    362
#define IDS_NEWNN                       363
#define IDS_NOCOMBINAISONKEYPTT         364
#define IDS_ADMIN                       365
#define IDS_OPPSW                       366
#define IDS_ENTERPSW                    367
#define IDS_DUPLEXNOTSUPPORTPOS         368
#define IDS_POSUSERS                    369
#define IDS_POSONLYDS                   370
#define IDS_SUREDELETECHAN              371
#define IDS_CHANDELETETITLE             372
#define IDS_CHANPSW                     373
#define IDS_COMPILEDON                  375
#define IDS_UNICODEENABLED              376
#define IDS_LOCALECHARS                 377
#define IDS_TTDLLVER                    378
#define IDS_TTDLLVERS                   379
#define IDS_SHELLEXECOPEN               380
#define IDS_RXTXPING                    381
#define IDS_RXTX                        382
#define IDS_AWAY                        383
#define IDS_FAILEDTOCONNECTLP           384
#define IDS_NEWUPDATEAVAILABLE          385
#define IDS_DISCONNECTCURRENT           386
#define IDS_FAILEDTOCONNECTCHECKHOSTVALID 387
#define IDS_TTFILEINCOMPATIBLE          388
#define IDS_MSGBOXTTFILELOADERROR       389
#define IDS_TTFILENOTVALIDHOST          390
#define IDS_UNABLETOPARSELINKADDR       391
#define IDS_DISCOBEFORERUN              392
#define IDS_FWFAILEDTOADD               393
#define IDS_RECSTARTFAILED              394
#define IDS_ERR                         395
#define IDS_RECORDINGFILE               396
#define IDS_FILEOPENFAILED              397
#define IDS_ALLFILESTYPE                398
#define IDS_SENDFILEFAILED              399
#define IDS_DLFILEFAILED                400
#define IDS_QUERYSERVSTATFAILED         401
#define IDS_SERVSTAT                    402
#define IDS_BROADMSG                    403
#define IDS_MSGTOBROAD                  404
#define IDS_ENABLEVT                    405
#define IDS_NOVIDEODEVICE               406
#define IDS_STARTVIDEODEVICEFAILED      407
#define IDS_INITIALIZEVIDEOCODECFAILED  408
#define IDS_CHANOP                      409
#define IDS_RESETPREF                   410
#define IDS_NEWCLIENTINSTAN             411
#define IDS_EXECUTEFAILED               412
#define IDS_ONLINEDLGID                 414
#define IDS_ONLINEDLGNICKNAME           415
#define IDS_ONLINEDLGSM                 416
#define IDS_ONLINEDLGUSERNAME           417
#define IDS_ONLINEDLGCHAN               418
#define IDS_ONLINEDLGIPADDR             419
#define IDS_ONLINEDLGVERS               420
#define IDS_STREAMDLGUNKFOR             421
#define IDS_STREAMDLGUNSPECIFIED        422
#define IDS_STREAMDLGSTEREO             423
#define IDS_STREAMDLGMONO               424
#define IDS_STREAMDLGMFT                425
#define IDS_STREAMDLGFAILEDUPDATE       426
#define IDS_STREAMDLGFAILEDRESUME       427
#define IDS_STREAMDLGFAILEDSTARTPB      428
#define IDS_LOADFILECLIENTSET           429
#define IDS_ADDTOFWEXCEP                430
#define IDS_BANTYPEDLGIPADDR            432
#define IDS_BANTYPEDLGUSERNAME          433
#define IDS_CHANDLGNOAUDIO              434
#define IDS_CHANDLGSPEEXVARIABLE        435
#define IDS_CHANDLGENTERACHANNAME       436
#define IDS_CHANDLGNOSLASH              437
#define IDS_CHANDLGVOIP                 438
#define IDS_CHANDLGMUSIC                439
#define IDS_CHATRICHBROADCAST           440
#define IDS_CHATRICHBROADCASTT          441
#define IDS_CHATRICHSERVERNAMEMOTD      442
#define IDS_CHATRICHSERVERNAMEMOTDD     443
#define IDS_CHATRICHJOINEDNEWCHAN       444
#define IDS_CHATRICHCHAN                445
#define IDS_CHATRICHTOPIC               446
#define IDS_CHATRICHDISKQUOTA           447
#define IDS_CHATRICHKBYTES              448
#define IDS_CLIENTPAGECANNOTUSESAMEPORTS 449
#define IDS_DESKTOPDLGLOW               450
#define IDS_DESKTOPDLGMEDIUM            451
#define IDS_DESKTOPDLGHIGH              452
#define IDS_DESKTOPDLGMAXIMUM           453
#define IDS_FILETABKB                   454
#define IDS_FILETABNAME                 455
#define IDS_FILETABSIZE                 456
#define IDS_FILETABUSER                 457
#define IDS_FILETRANSFERKBYTES          458
#define IDS_FILETRANSFERBYTES           459
#define IDS_FILETRANSFERSPEED           460
#define IDS_FILETRANSFERSPEEDB          461
#define IDS_FILETRANSFERBYTESSEC        462
#define IDS_FILETRANSFERPROGRESSCOMPLETED 463
#define IDS_FILETRANSFERFAILED          464
#define IDS_GENERATETTFILEANY           465
#define IDS_GENERATETTFILEEXTFILE       466
#define IDS_GENERATETTFILEFAILEDTOSAVE  467
#define IDS_GENERATETTFILESAVE          468
#define IDS_HOSTMANAGERFILLALLFIELDS    469
#define IDS_HOSTMANAGERCANNOTDELPUBSERV 470
#define IDS_HOSTMANAGERDELHOST          471
#define IDS_HOSTMANAGERPUBLIC           472
#define IDS_HOSTMANAGERHOSTFILES        473
#define IDS_HOSTMANAGERALLFILES         474
#define IDS_HOSTMANAGERFILENOTCONTAINVALIDENTRY 475
#define IDS_KEYCOMPERROR                476
#define IDS_MEDIASTORAGEWAVEFORMAT      477
#define IDS_MEDIASTORAGEOGGFORMAT       478
#define IDS_MEDIASTORAGEMP3FORMAT16     479
#define IDS_MEDIASTORAGEMP3FORMAT32     480
#define IDS_MEDIASTORAGEMP3FORMAT64     481
#define IDS_MEDIASTORAGEMP3FORMAT128    482
#define IDS_MEDIASTORAGEMP3FORMAT256    483
#define IDS_MSGDLGFAILEDTOSEND          484
#define IDS_POSUSERDISTCOORDO           485
#define IDS_SHORTCUTPAGECLEAR           486
#define IDS_SOUNDEVENTSWAVFILES         487
#define IDS_SOUNDSYSTEMNOINPUTDEVICESEL 488
#define IDS_SOUNDSYSTEMNOOUTPUTDEVICESEL 489
#define IDS_SOUNDSYSTEMFAILEDTOINITIALIZE 490
#define IDS_USERACCOUNTCREATEANONYMOUS  491
#define IDS_USERACCOUNTADDUPDATE        492
#define IDS_USERDESKTOPLOCALDESKTOP     493
#define IDS_USERDESKTOPDESKTOP          494
#define IDS_USERVIDEOLOCALVIDEO         495
#define IDS_USERVIDEOVIDEO              496
#define IDS_USERVOLUMETITLEWINDOW       497
#define IDS_VIDEOCAPTUREFAILED          498
#define IDS_WEBLOGINFBLOGOUT            499
#define IDS_WEBLOGINFBLOGIN             500
#define MAX_STRING_LENGTH               511
#define IDS_APPTITLEUNRELEASED          512
#define IDS_APPTITLEPROV                513
#define IDS_APPTITLEPRO                 514
#define IDS_APPTITLENPROV               515
#define IDS_APPTITLENPRO                516
#define IDS_CMDERR_SYNTAX_ERROR         517
#define IDS_CMDERR_UNKNOWN_COMMAND      518
#define IDS_CMDERR_MISSING_PARAMETER    519
#define IDS_CMDERR_INCOMPATIBLE_PROTOCOLS 520
#define IDS_CMDERR_UNKNOWN_AUDIOCODEC   521
#define IDS_CMDERR_INVALID_USERNAME     522
#define IDS_CMDERR_INCORRECT_CHANNEL_PASSWORD 523
#define IDS_CMDERR_INVALID_ACCOUNT      524
#define IDS_CMDERR_MAX_SERVER_USERS_EXCEEDED 525
#define IDS_CMDERR_MAX_CHANNEL_USERS_EXCEEDED 526
#define IDS_CMDERR_SERVER_BANNED        527
#define IDS_CMDERR_NOT_AUTHORIZED       528
#define IDS_CMDERR_MAX_DISKUSAGE_EXCEEDED 529
#define IDS_CMDERR_INCORRECT_OP_PASSWORD 530
#define IDS_CMDERR_AUDIOCODEC_BITRATE_LIMIT_EXCEEDED 531
#define IDS_CMDERR_MAX_LOGINS_PER_IPADDRESS_EXCEEDED 532
#define IDS_CMDERR_MAX_CHANNELS_EXCEEDED 533
#define IDS_CMDERR_COMMAND_FLOOD        534
#define IDS_CMDERR_CHANNEL_BANNED       535
#define IDS_CMDERR_NOT_LOGGEDIN         536
#define IDS_CMDERR_ALREADY_LOGGEDIN     537
#define IDS_CMDERR_NOT_IN_CHANNEL       538
#define IDS_CMDERR_ALREADY_IN_CHANNEL   539
#define IDS_CMDERR_CHANNEL_ALREADY_EXISTS 540
#define IDS_CMDERR_CHANNEL_NOT_FOUND    541
#define IDS_CMDERR_BAN_NOT_FOUND        542
#define IDS_CMDERR_FILETRANSFER_NOT_FOUND 543
#define IDS_CMDERR_OPENFILE_FAILED      544
#define IDS_CMDERR_ACCOUNT_NOT_FOUND    545
#define IDS_CMDERR_FILE_NOT_FOUND       546
#define IDS_CMDERR_FILE_ALREADY_EXISTS  547
#define IDS_CMDERR_FILESHARING_DISABLED 548
#define IDS_CMDERR_CHANNEL_HAS_USERS    549
#define IDS_CMDERR_LOGINSERVICE_UNAVAILABLE 550
#define IDS_CMDERR_USER_NOT_FOUND       551
#define IDC_SLIDER_VOICEACT             1001
#define IDC_SLIDER_VOLUME               1002
#define IDC_EDIT_HOSTTCPPORT            1003
#define IDC_PROGRESS_VOICEACT           1004
#define IDC_EDIT_HOSTUDPPORT            1005
#define IDC_LIST_FILES                  1006
#define IDC_EDIT_PASSWORD               1007
#define IDC_STATIC_MIKE                 1008
#define IDC_CHECK_AUTOJOINROOT          1009
#define IDC_STATIC_APPTITLE             1010
#define IDC_STATIC_HOSTTCPPORT          1012
#define IDC_STATIC_SPLITTER             1013
#define IDC_TREE_SESSION                1014
#define IDC_EDIT_MOTD                   1015
#define IDC_STATIC_HOSTUDPPORT          1016
#define IDC_STATIC_VOLUME               1017
#define IDC_CHECK_SHOWUSERCOUNT         1020
#define IDC_CHECK_POSITIONING           1021
#define IDC_CHECK_IDLEVOX               1022
#define IDC_CHECK_MANUAL                1024
#define IDC_STATIC_VOICEACT             1027
#define IDC_STATIC_VOLUME2              1028
#define IDC_EDIT_CHANPASSWORD           1029
#define IDC_BUTTON_CONNECT              1030
#define IDC_EDIT_CHANNAME               1031
#define IDC_EDIT_CHANTOPIC              1032
#define IDC_EDIT_INACTIVITY             1033
#define IDC_STATIC_DISABLED0            1034
#define IDC_STATIC_USERID               1035
#define IDC_STATIC_NICKNAME             1036
#define IDC_STATIC_DISABLED1            1037
#define IDC_STATIC_INTRO                1042
#define IDC_SLIDER_MEDIAFILEVOL         1043
#define IDC_CHECK_WEBSITE               1044
#define IDC_STATIC_PACKETLOSS           1045
#define IDC_STATIC_FILESIZE             1047
#define IDC_CHECK_QUITCLEAR             1048
#define IDC_SLIDER_VOICEVOL             1049
#define IDC_STATIC_SFILESIZE            1050
#define IDC_CHECK_DBCLICKJOIN           1051
#define IDC_EDIT_NICKNAME               1052
#define IDC_CHECK_MSGTIMESTAMP          1053
#define IDC_CHECK_PUSHTOTALK            1054
#define IDC_STATIC_GRPSTATUS            1055
#define IDC_CHECK_VOICEACT              1056
#define IDC_STATIC_AWAYMSG              1057
#define IDC_EDIT_KEYCOMB                1058
#define IDC_STATIC_CHNAME               1059
#define IDC_CHECK_TRAY                  1060
#define IDC_STATIC_CHTOPIC              1061
#define IDC_STATIC_CHPASSWORD           1063
#define IDC_RADIO_WASAPI                1065
#define IDC_STATIC_MAXLOGINSIP          1067
#define IDC_RADIO_DIRECTSOUND           1068
#define IDC_COMBO_INPUTDRIVER           1070
#define IDC_COMBO_OUTPUTDRIVER          1072
#define IDC_STATIC_PASSWORD             1073
#define IDC_COMBO_SRATE                 1074
#define IDC_STATIC_HOSTADDR             1075
#define IDC_COMBO_CODECAPP              1076
#define IDC_STATIC_AUDCHANNELS          1077
#define IDC_STATIC_APPLICATION          1078
#define IDC_STATIC_GRPUSRRIGHTS         1079
#define IDC_SLIDER_QUALITY              1080
#define IDC_STATIC_MAXLOGINSBAN         1081
#define IDC_STATIC_THROUGHPUT           1082
#define IDC_STATIC_USERNAME             1083
#define IDC_STATIC_OPTAUTH              1084
#define IDC_STATIC_GRPHOSTS             1085
#define IDC_EDIT_INPUT                  1086
#define IDC_EDIT_CHPASSWD               1087
#define IDC_STATIC_GRPHOSTPROP          1088
#define IDC_STATIC_MESSAGE              1089
#define IDC_EDIT_VIDEO                  1091
#define IDC_STATIC_ENTRYNAME            1092
#define IDC_STATIC_VU                   1093
#define IDC_STATIC_DEFLOCALUDP          1095
#define IDC_EDIT_USERSPEAK              1096
#define IDC_STATIC_DEFHOSTPORT          1098
#define IDC_COMBO_HOSTADDRESS           1099
#define IDC_STATIC_DEFUDPPORT           1101
#define IDC_CHECK_AUTOCONNECT           1102
#define IDC_STATIC_GRPKEYCOMP           1104
#define IDC_STATIC_KEYCOMPDESCRIP       1106
#define IDC_STATIC_CURKEYCOMP           1108
#define IDC_RADIO_ONLINE                1109
#define IDC_STATIC_KEYCOMPDLGCLOSES     1111
#define IDC_RADIO_AWAY                  1112
#define IDC_STATIC_HISTORY              1114
#define IDC_EDIT_AWAYMESSAGE            1115
#define IDC_STATIC_3DDESCRIP            1117
#define IDC_RADIO_QUESTION              1118
#define IDC_EDIT_USERID                 1119
#define IDC_STATIC_IPADDR               1123
#define IDC_EDIT_TOTALTX                1124
#define IDC_EDIT_LOCALTCPPORT           1126
#define IDC_STATIC_VOICELOSS            1127
#define IDC_EDIT_LOCALUDPPORT           1128
#define IDC_EDIT_VOICE                  1129
#define IDC_EDIT_MAXBITRATE             1130
#define IDC_CHECK_RECONNECT             1131
#define IDC_EDIT_CLIENTVER              1132
#define IDC_RICHEDIT_MESSAGE            1135
#define IDC_EDIT_VIDEOTX                1137
#define IDC_RICHEDIT_HISTORY            1138
#define IDC_STATIC_GRPADVANCED          1142
#define IDC_STATIC_CLIENTVER            1148
#define IDC_STATIC_GRPCLIENT            1149
#define IDC_CHECK_STARTMINIMIZED        1150
#define IDC_STATIC_GRPLOCALPORTS        1151
#define IDC_STATIC_MFVFLOSS             1152
#define IDC_STATIC_LOCALTCPPORT         1153
#define IDC_LIST_HOSTS                  1154
#define IDC_STATIC_DEFLOCALTCP          1155
#define IDC_STATIC_GRPUSERSETTINGS      1157
#define IDC_STATIC_GRPSPEECH            1158
#define IDC_STATIC_SECINACT             1160
#define IDC_EDIT_ENTRYNAME              1161
#define IDC_STATIC_SETAWAY              1162
#define IDC_STATIC_SERVERNAME           1163
#define IDC_BUTTON_DELETE               1164
#define IDC_STATIC_LOCALUDPPORT         1166
#define IDC_BUTTON_ADDUPDATE            1167
#define IDC_BUTTON_NEW                  1169
#define IDC_BUTTON_GENTT                1170
#define IDC_STATIC_MOTD                 1172
#define IDC_BUTTON_TEST                 1175
#define IDC_STATIC_GRPSNDEVENT          1186
#define IDC_STATIC_RECORDERFREQ         1188
#define IDC_STATIC_INPUT                1189
#define IDC_STATIC_VOICEQUALITY         1190
#define IDC_STATIC_OUTPUT               1191
#define IDC_STATIC_STHROUGHPUT          1192
#define IDC_CHECK_DENOISE               1193
#define IDC_EDIT_KEYCOMP                1195
#define IDC_BUTTON_SETUPKEYS            1196
#define IDC_STATIC_KEYCOMP              1198
#define IDC_STATIC_GRPWINDOW            1199
#define IDC_STATIC_FONT                 1200
#define IDC_STATIC_NEWMESSAGE           1201
#define IDC_STATIC_CLKFINISH            1202
#define IDC_STATIC_TYPENICK             1203
#define IDC_RICHEDIT_CHANMESSAGES       1204
#define IDC_EDIT_CHANMESSAGE            1206
#define IDC_CHECK_POPUPMSG              1208
#define IDC_STATIC_TRANSDESCRIP         1209
#define IDC_BUTTON_FONT                 1210
#define IDC_STATIC_GRPSOUNDSYSTEM       1211
#define IDC_STATIC_FONTNAME             1212
#define IDC_STATIC_SOUNDSYSDESCRIP      1213
#define IDC_STATIC_WEBMCODECDEV         1214
#define IDC_STATIC_TESTDESCRIP          1215
#define IDC_EDIT_USERTYPE               1216
#define IDC_CHECK_CHANNELSTEMP          1217
#define IDC_CHECK_CHANNELSPERMANENT     1218
#define IDC_EDIT_IPADDR                 1220
#define IDC_CHECK_ALWAYSONTOP           1221
#define IDC_STATIC_COOR                 1222
#define IDC_STATIC_ROOM                 1223
#define IDC_BUTTON_DEFAULT              1225
#define IDC_STATIC_COPYRIGHT            1226
#define IDC_STATIC_IMAGE                1227
#define IDC_STATIC_AUTHOR               1228
#define IDC_STATIC_SPEEXCODECDEV        1229
#define IDC_STATIC_GRPCHANNEL           1230
#define IDC_BUTTON_SEND                 1231
#define IDC_STATIC_OPUSCODECDEV         1232
#define IDC_VERT_SPLITTER               1233
#define IDC_STATIC_VERSION              1234
#define IDC_STATIC_                     1235
#define IDC_STATIC_WIZWELCOME           1236
#define IDC_STATIC_WIZCOMPLETED         1237
#define IDC_STATIC_PBSET                1238
#define IDC_COMBO_LANGUAGE              1239
#define IDC_STATIC_TRANSLATOR           1240
#define IDC_STATIC_UILANGUAGE           1241
#define IDC_EDIT_WIZCOMPLETED           1242
#define IDC_STATIC_MIXERDEVICE          1243
#define IDC_STATIC_TRANSLATOR2          1244
#define IDC_CHECK_UILANGUAGE            1245
#define IDC_CHECK_AUTOCLOSE             1246
#define IDC_TAB_CTRL                    1251
#define IDC_PROGRESS1                   1252
#define IDC_STATIC_FILETXT              1253
#define IDC_STATIC_TRANSFERRED          1254
#define IDC_STATIC_FILENAME             1255
#define IDC_BUTTON_HKVA                 1257
#define IDC_EDIT_HKVA                   1258
#define IDC_STATIC_VA                   1260
#define IDC_STATIC_VOLUMEPLUS           1261
#define IDC_STATIC_VOLUMEMINUS          1262
#define IDC_EDIT_HKIV                   1263
#define IDC_BUTTON_HKIV                 1264
#define IDC_EDIT_HKLV                   1265
#define IDC_BUTTON_HKLV                 1266
#define IDC_STATIC_MUTEALL              1267
#define IDC_STATIC_IVG                  1268
#define IDC_EDIT_HKMA                   1269
#define IDC_BUTTON_HKMA                 1270
#define IDC_EDIT_HKIVG                  1271
#define IDC_BUTTON_HKIVG                1272
#define IDC_EDIT_HKLVG                  1273
#define IDC_BUTTON_HKLVG                1274
#define IDC_EDIT_HKMIN                  1275
#define IDC_BUTTON_HKMIN                1276
#define IDC_STATIC_LVG                  1277
#define IDC_STATIC_KBSHORTCUTS          1278
#define IDC_STATIC_COMPILED             1283
#define IDC_BUTTON_OPEN                 1284
#define IDC_STATIC_OPPASSWD             1287
#define IDC_EDIT_OPPASSWD               1288
#define IDC_EDIT_MAXUSERS               1290
#define IDC_EDIT_DISKQUOTA              1291
#define IDC_STATIC_SRVSETTINGS          1292
#define IDC_STATIC_DISKQUOTA            1293
#define IDC_STATIC_MAXUSERS             1294
#define IDC_STATIC_GRPJOINCHAN          1295
#define IDC_STATIC_USERTIME             1296
#define IDC_EDIT_CHANNEL                1297
#define IDC_STATIC_AUDIOCODEC           1298
#define IDC_STATIC_ACTACCOUNTS          1299
#define IDC_CHECK_SINGLETXCHANNEL       1303
#define IDC_CHECK_CHANNELPERMANENT      1304
#define IDC_COMBO_AUDIOCHANNELS         1305
#define IDC_EDIT_USERNAME               1306
#define IDC_STATIC_USERTYPE             1308
#define IDC_CHECK_AUTOSAVE              1309
#define IDC_CHECK_VIEWALLUSERS          1311
#define IDC_CHECK_USERBCAST             1312
#define IDC_CHECK_TRANSMITVOICE         1315
#define IDC_CHECK_TRANSMITVIDEOFILE     1317
#define IDC_EDIT_TCPPORT                1318
#define IDC_EDIT_SRVNAME                1319
#define IDC_EDIT_USERTIMEOUT            1320
#define IDC_EDIT_UDPPORT                1321
#define IDC_LIST_ACCOUNTS               1322
#define IDC_RADIO_ADMIN                 1323
#define IDC_BUTTON_ADD                  1324
#define IDC_BUTTON_DEL                  1325
#define IDC_LIST_BANNED                 1326
#define IDC_LIST_UNBANNED               1327
#define IDC_BUTTON_UNBAN                1328
#define IDC_BUTTON_BAN                  1329
#define IDC_STATIC_BANNED               1330
#define IDC_STATIC_UNBANNED             1331
#define IDC_CHECK_CHECKUPDATES          1332
#define IDC_CHECK_PUBLICSERVERS         1334
#define IDC_CHECK_DOUBLELOGIN           1335
#define IDC_COMBO_CHANNELS              1338
#define IDC_CHECK_CLASSROOM             1339
#define IDC_EDIT_TOTAL                  1340
#define IDC_CHECK_FORCEAGC              1341
#define IDC_SLIDER_GAINLEVEL            1342
#define IDC_STATIC_GAINLEVEL            1344
#define IDC_STATIC_GAINLEVEL2           1345
#define IDC_COMBO_CODEC                 1346
#define IDC_STATIC_GAINLEVEL3           1346
#define IDC_CHECK_DTX                   1347
#define IDC_STATIC_GAINLEVEL4           1347
#define IDC_EDIT_BITRATE                1348
#define IDC_STATIC_DENOISE              1348
#define IDC_STATIC_BITRATE              1349
#define IDC_STATIC_MAXBITRATE           1350
#define IDC_STATIC_BPS1                 1351
#define IDC_STATIC_BPS2                 1352
#define IDC_EDIT_SRVVERSION             1353
#define IDC_EDIT_AUDIOTX                1354
#define IDC_SPIN_DELAY                  1355
#define IDC_SPIN_VIDBITRATE             1356
#define IDC_BUTTON_USER2USERBROWSE      1357
#define IDC_LIST_ONLINEUSERS            1358
#define IDC_BUTTON_AUDIOBROWSE          1359
#define IDC_BUTTON_CHANLOGBROWSE        1360
#define IDC_EDIT_TXDELAY                1361
#define IDC_STATIC_TXINTERVAL           1362
#define IDC_STATIC_TXI1                 1363
#define IDC_CHECK_SINGLEFILE            1364
#define IDC_CHECK_SEPARATEFILES         1365
#define IDC_COMBO_AFF                   1366
#define IDC_EDIT_AUDIOFOLDER            1367
#define IDC_COMBO_VIDDEV                1368
#define IDC_STATIC_VIDCAPDEV            1369
#define IDC_COMBO_VIDRES                1370
#define IDC_RADIO_VIDRGB32              1371
#define IDC_RADIO_VIDI420               1372
#define IDC_RADIO_VIDYUY2               1373
#define IDC_BUTTON_VIDTEST              1374
#define IDC_COMBO_VIDCODEC              1376
#define IDC_EDIT_VIDBITRATE             1378
#define IDC_RADIO_SHAREDESKTOP          1379
#define IDC_RADIO_SHAREACTIVE           1380
#define IDC_RADIO_SHARESPECIFIC         1381
#define IDC_COMBO_WINDOWTITLE           1382
#define IDC_COMBO_COLORMODE             1383
#define IDC_CHECK_INTERVAL              1384
#define IDC_SPIN_UPDATEINTERVAL         1385
#define IDC_EDIT_INTERVAL               1386
#define IDC_CHECK_SUBUSERMSG            1387
#define IDC_CHECK_SUBCHANMSG            1388
#define IDC_CHECK_SUBBCAST              1389
#define IDC_STATIC_DEFSUBSCRIPTIONS     1390
#define IDC_CHECK_SUBVOICE              1391
#define IDC_CHECK_SUBVIDEO              1392
#define IDC_CHECK_SUBDESKTOP            1393
#define IDC_STATIC_TCPPORT              1394
#define IDC_STATIC_UDPPORT              1395
#define IDC_STATIC_MAXABPS              1396
#define IDC_STATIC_KBPS                 1397
#define IDC_STATIC_KBYPS1               1398
#define IDC_STATIC_KBYPS2               1399
#define IDC_STATIC_KBYPS3               1400
#define IDC_STATIC_AUDTX                1401
#define IDC_STATIC_VIDTX                1402
#define IDC_STATIC_TOTALTX              1403
#define IDC_STATIC_SERVERVERSION        1404
#define IDC_STATIC_SERVERINFO           1405
#define IDC_STATIC_AUDCODECLIMIT        1406
#define IDC_STATIC_SRVBWLIMITS          1407
#define IDC_STATIC_CODEC                1411
#define IDC_STATIC_AUDCFG               1412
#define IDC_STATIC_VOLLEVEL             1413
#define IDC_STATIC_MINRESTORE           1414
#define IDC_STATIC_CURUSERS             1415
#define IDC_STATIC_AUDSTORAGE           1416
#define IDC_STATIC_STORMODE             1417
#define IDC_STATIC_AFF                  1418
#define IDC_STATIC_AUDFOLDER            1419
#define IDC_STATIC_VIDCAP               1420
#define IDC_STATIC_VIDRES               1421
#define IDC_STATIC_IMGFMT               1422
#define IDC_STATIC_VIDCODECSETTINGS     1423
#define IDC_STATIC_BPS                  1424
#define IDC_STATIC_VBRKBPS              1425
#define IDC_STATIC_WNDSHARE             1426
#define IDC_STATIC_COLORMODE            1427
#define IDC_STATIC_MSEC                 1428
#define IDC_STATIC_TOTAL                1429
#define IDC_STATIC_VOICE                1430
#define IDC_STATIC_VIDEO                1431
#define IDC_STATIC_KBPS1                1432
#define IDC_STATIC_KBPS2                1433
#define IDC_STATIC_KBPS3                1434
#define IDC_STATIC_MEDIAFILERXTX        1435
#define IDC_STATIC_KBPS4                1436
#define IDC_BUTTON_DELENTRY             1437
#define IDC_STATIC_DESKTOPTX            1438
#define IDC_EDIT_DESKTOPTX              1439
#define IDC_CHECK_TRANSMITDESKTOP       1440
#define IDC_CHECK_SHOWMOTD              1441
#define IDC_STATIC_NOTE                 1443
#define IDC_EDIT_NOTE                   1444
#define IDC_STATIC_INITCHANNEL          1445
#define IDC_LIST_AVAILCHANNELS          1446
#define IDC_LIST_SELECTEDCHANNELS       1447
#define IDC_BUTTON_ADDCHANNEL           1448
#define IDC_BUTTON_DELCHANNEL           1449
#define IDC_COMBO_INITCHANNEL           1450
#define IDC_STATIC_SELCHANNELS          1451
#define IDC_STATIC_AVAILCHANNELS        1452
#define IDC_STATIC_GRPAUTOOP            1453
#define IDC_CHECK_ECHOCANCEL            1456
#define IDC_CHECK_OPRECVONLY            1460
#define IDC_STATIC_INPUT_SAMPLERATES    1461
#define IDC_STATIC_OUTPUT_SAMPLERATES   1462
#define IDC_STATIC_OUTPUTPROP           1463
#define IDC_STATIC_INPUTPROP            1464
#define IDC_CHECK_ENCRYPTED             1465
#define IDC_STATIC_SAVESERVERINFO       1468
#define IDC_STATIC_KBPS5                1469
#define IDC_STATIC_SORTCHANNELS         1470
#define IDC_STATIC_AUDIOFORMAT          1471
#define IDC_STATIC_VIDEOFORMAT          1472
#define IDC_STATIC_MOTD_TEXT            1473
#define IDC_STATIC_KBYPS4               1474
#define IDC_STATIC_AUDFMT               1475
#define IDC_STATIC_VIDFMT               1476
#define IDC_STATIC_MEDIAGRP             1477
#define IDC_STATIC_MEDIAFILE            1478
#define IDC_STATIC_KBYPS5               1480
#define IDC_RADIO_DEFAULTUSER           1481
#define IDC_CHECK_TRANSMITDESKTOPINPUT  1482
#define IDC_CHECK_KICKUSERS             1483
#define IDC_CHECK_BANUSERS              1484
#define IDC_CHECK_MOVEUSERS             1485
#define IDC_CHECK_CHANNELOP             1486
#define IDC_CHECK_UPLOADFILES           1487
#define IDC_CHECK_DOWNLOADFILES         1488
#define IDC_CHECK_UPDATESERVER          1489
#define IDC_CHECK_TRANSMITAUDIOFILE     1490
#define IDC_CHECK_TRANSMITVIDEOCAPTURE  1491
#define IDC_STATIC_VOICEVOL             1492
#define IDC_CHECK_MUTELEFTVOICE         1493
#define IDC_CHECK_MUTERIGHTVOICE        1494
#define IDC_CHECK_NOVOICEACT            1495
#define IDC_STATIC_MEDIAFILEVOL         1496
#define IDC_CHECK_MUTELEFTMEDIAFILE     1497
#define IDC_CHECK_MUTERIGHTMEDIAFILE    1498
#define IDC_EDIT_FILESRXTX              1499
#define IDC_EDIT_USERSSERVED            1500
#define IDC_EDIT_MEDIAFILERXTX          1501
#define IDC_EDIT_DESKTOPRXTX            1502
#define IDC_STATIC_DESKTOPRXTX          1503
#define IDC_STATIC_FILESRXTX            1504
#define IDC_EDIT_MEDIAFILETX            1505
#define IDC_STATIC_MEDIAFILETX          1506
#define IDC_STATIC_SERVERABUSE          1507
#define IDC_EDIT_LOGINBAN               1508
#define IDC_EDIT_IPLOGINS               1509
#define IDC_STATIC_USERSPEAK            1510
#define IDC_STATIC_KBPS6                1511
#define IDC_STATIC_USERSSERVED          1512
#define IDC_CHECK_SUBMEDIAFILE          1513
#define IDC_CHECK_AGC                   1514
#define IDC_BUTTON_REFRESHSND           1515
#define IDC_CHECK_NORECORD              1516
#define IDC_STATIC_MFAUDIOLOSS          1517
#define IDC_STATIC_MFVIDEOLOSS          1518
#define IDC_STATIC_SMFAUDIO             1519
#define IDC_CHECK_VUMETER               1520
#define IDC_EDIT_CHANLOGFOLDER          1521
#define IDC_EDIT_TEXTLOGFOLDER          1522
#define IDC_STATIC_TXTMSGGRP            1523
#define IDC_STATIC_CHANLOGFOLDER        1524
#define IDC_STATIC_USER2USERLOGFOLDER   1525
#define IDC_STATIC_GRPCLIENTSETTINGS    1526
#define IDC_CHECK_CLIENTOVERRIDE        1527
#define IDC_STATIC_GENDER               1528
#define IDC_RADIO_MALE                  1529
#define IDC_RADIO_FEMALE                1530
#define IDC_BUTTON_SAVETTFILE           1531
#define IDC_EDIT_LIMITTEXT              1532
#define IDC_SPIN_TEXTLEN                1533
#define IDC_STATIC_LIMITTEXT            1534
#define IDC_STATIC_VIDCAPCODECSETTINGS  1535
#define IDC_SLIDER_MEDIASTREAM_VOL      1536
#define IDC_STATIC_MEDIASTREAMVOL       1537
#define IDC_BUTTON_IMPORTTTILE          1538
#define IDC_CHECK_SHOWUSERNAME          1539
#define IDC_STATIC_CLIENTNAME           1540
#define IDC_EDIT_CLIENTNAME             1541
#define IDC_TREE_TTS                    1542
#define IDC_STATIC_TTS                  1543
#define IDC_TREE_SOUNDEVENTS            1544
#define IDC_TAB_USERACCOUNT             1545
#define IDC_STATIC_GRPACCOUNT           1546
#define IDC_STATIC_GRPABUSE             1547
#define IDC_STATIC_PREVENTSPAM          1548
#define IDC_COMBO_CMDLIMIT              1549
#define IDC_STATIC_CMDLIMIT             1550
#define IDC_COMBO_USERNAME              1551
#define IDC_EXPLORER1                   1552
#define IDC_BUTTON_PROFILE              1553
#define IDC_CHECK_CHANGENICKNAME        1554
#define IDC_COMBO_BANTYPE               1555
#define IDC_COMBO_INPUT                 1556
#define IDC_COMBO_SORTCHANNELS          1557
#define IDC_CHECK_RECORDVOICE           1558
#define IDC_COMBO_FILENAME              1559
#define IDC_EDIT_BEARWAREID             1560
#define IDC_BUTTON_SETUPBEARWARE        1561
#define IDC_STATIC_BEARWARELOGIN        1562
#define IDC_STATIC_BEARWARECREATE       1563
#define IDC_STATIC_BEARWAREAUTH         1564
#define IDC_BUTTON_BEARWARECREATE       1565
#define IDC_CHECK_SHOWDISCONNECTED      1566
#define IDC_CHECK_VBR                   1567
#define IDC_COMBO_OPUSFRAMESIZES        1568
#define IDC_STATIC_OPUSFRMSIZE          1569
#define IDC_STATIC_DURATION             1570
#define IDC_STATIC_SDURATION            1571
#define IDC_COMBO_AUDIOPREPROCESSOR     1572
#define IDC_BUTTON_AUDIOSETUP           1573
#define IDC_SLIDER_OFFSET               1574
#define IDC_BUTTON_STOP                 1575
#define IDC_BUTTON_PLAY                 1576
#define IDC_STATIC_TIMEOFFSET           1577
#define IDC_STATIC_AGCGRP               1578
#define IDC_STATIC_DENOISEGRP           1579
#define IDC_EDIT_GAINLEVEL              1580
#define IDC_SPIN_GAINLEVEL              1581
#define IDC_EDIT_MAXGAIN                1582
#define IDC_SPIN_MAXGAIN                1583
#define IDC_EDIT_GAININC                1584
#define IDC_SPIN_GAININC                1585
#define IDC_EDIT_GAINDEC                1586
#define IDC_SPIN_GAINDEC                1587
#define IDC_EDIT_DENOISE                1588
#define IDC_SPIN_DENOISE                1589
#define IDC_BUTTON_DEFAULT2             1590
#define IDC_CHECK_MUTELEFT              1591
#define IDC_CHECK_MUTERIGHT             1592
#define IDC_CHECK_REPEAT                1593
#define IDC_STATIC_STARTPOS             1594
#define IDC_STATIC_AUDIOPREPROCESSOR    1595
#define IDC_STATIC_TESTPLAYBACK         1596
#define ID_HELP_WHATISMYIP              32791
#define ID_USERS_OP                     32798
#define ID_CHANNELS_VIEWCHANNELMESSAGES 32801
#define ID_ME_USESPEECHONEVENTS         32805
#define ID_HELP_RUNWIZARD               32814
#define ID_USERS_POSITIONUSERS          32815
#define ID_USERS_MUTEALL                32816
#define ID_FILE_CONNECT                 32818
#define ID_HELP_MANUAL                  32819
#define ID_HELP_ABOUT                   32820
#define ID_FILE_PREFERENCES             32821
#define ID_FILE_EXIT                    32822
#define ID_ME_ENABLEHOTKEY              32823
#define ID_ME_ENABLEVOICEACTIVATION     32824
#define ID_HELP_WEBSITE                 32825
#define ID_ME_CHANGESTATUS              32826
#define ID_POPUP_RESTORE                32829
#define ID_ME_CHANGENICK                32830
#define ID_CHANNELS_VIEWCHANNELINFO     32831
#define ID_USERS_VOLUME                 32833
#define ID_USERS_VIEWINFO               32835
#define ID_CHANNELS_CREATECHANNEL       32837
#define ID_CHANNELS_JOINCHANNEL         32838
#define ID_USERS_MESSAGES               32839
#define ID_POPUP_CUT                    32840
#define ID_POPUP_COPY                   32841
#define ID_POPUP_CLEARALL               32842
#define ID_POPUP_DELETE                 32843
#define ID_POPUP_SELECTALL              32844
#define ID_POPUP_UNDO                   32845
#define ID_POPUP_PASTE                  32846
#define ID_CHANNELS                     32847
#define ID_USERS                        32848
#define ID_FILE                         32849
#define ID_ME                           32850
#define ID_ADVANCED                     32851
#define ID_SUBSCRIPTIONS                32853
#define ID_MUTE                         32854
#define ID_KICK                         32855
#define ID_CHANNELS_UPLOADFILE          32857
#define ID_CHANNELS_DOWNLOADFILE        32858
#define ID_CHANNELS_DELETEFILE          32859
#define ID_CHANNELS_LEAVECHANNEL        32864
#define ID_CHANNELS_DELETECHANNEL       32866
#define ID_CHANNELS_UPDATECHANNEL       32867
#define ID_SERVER_SERVERPROPERTIES      32868
#define ID_SERVER_LISTUSERACCOUNTS      32869
#define ID_SERVER                       32870
#define ID_SERVER_SAVECONFIGURATION     32871
#define ID_ADVANCED_STOREFORMOVE        32877
#define ID_ADVANCED_MOVEUSER            32878
#define ID_SERVER_LISTBANNEDUSERS       32882
#define ID_USERS_KICKANDBAN             32885
#define ID_USERS_STORECONVERSATIONSTODISK 32888
#define ID_ADVANCED_MOVEUSERDIALOG      32890
#define ID_SUBSCRIPTIONS_USERMESSAGES   32892
#define ID_SUBSCRIPTIONS_CHANNELMESSAGES 32893
#define ID_SUBSCRIPTIONS_BROADCASTMESSAGES 32894
#define ID_SUBSCRIPTIONS_VOICE          32895
#define ID_SUBSCRIPTIONS_VIDEO          32896
#define ID_SUBSCRIPTIONS_INTERCEPTVOICE 32897
#define ID_SUBSCRIPTIONS_INTERCEPTUSERMESSAGES 32898
#define ID_SUBSCRIPTIONS_INTERCEPTCHANNELMESSAGES 32899
#define ID_SUBSCRIPTIONS_INTERCEPTVIDEO 32900
#define ID_ADVANCED_ALLOWVOICETRANSMISSION 32901
#define ID_ADVANCED_ALLOWVIDEOTRANSMISSION 32902
#define ID_SERVER_SERVERSTATISTICS      32903
#define ID_SERVER_ONLINEUSERS           32904
#define ID_POPUP_KICK                   32905
#define ID_POPUP_KICKANDBAN             32906
#define ID_POPUP_OP                     32907
#define ID_SERVER_BROADCASTMESSAGE      32908
#define ID_ME_ENABLEVIDEOTRANSMISSION   32909
#define ID_SUBSCRIPTIONS_DESKTOP        32914
#define ID_SUBSCRIPTIONS_INTERCEPTDESKTOP 32915
#define ID_ME_ENABLEDESKTOPSHARING      32916
#define ID_POPUP_COPYUSERINFORMATION    32921
#define ID_CHANNELS_STREAMMEDIAFILETOCHANNEL 32922
#define ID_SUBSCRIPTIONS_DESKTOPACCES   32923
#define ID_USERS_ALLOWDESKTOPACCESS     32924
#define ID_POPUP_REQUESTDESKTOPACCESS   32925
#define ID_USERS_MUTE_VOICE             32928
#define ID_USERS_MUTE_MEDIAFILE         32929
#define ID_USERS_KICKCHANNEL            32930
#define ID_USERS_KICKFROMSERVER         32931
#define ID_ADVANCED_INCVOLUMEVOICE      32932
#define ID_ADVANCED_LOWERVOLUMEVOICE    32933
#define ID_ADVANCED_INCVOLUMEMEDIAFILE  32934
#define ID_ADVANCED_LOWERVOLUMEMEDIAFILE 32935
#define ID_ADVANCED_ALLOWDESKTOPTRANSMISSION 32936
#define ID_ADVANCED_ALLOWMEDIAFILETRANSMISSION 32937
#define ID_SUBSCRIPTIONS_MEDIAFILESTREAM 32938
#define ID_SUBSCRIPTIONS_INTERCEPTMEDIAFILESTREAM 32939
#define ID_USERS_USERINFO               32940
#define ID_USERINFO_SPEAKUSERINFO       32941
#define ID_CHANNELS_CHANNELINFO         32942
#define ID_CHANNELINFO_SPEAKCHANNELINFO 32943
#define ID_HELP_RESETPREFERENCESTODEFAULT 32944
#define ID_ADVANCED_ALLOWALLVOICETRANSMISSION 32945
#define ID_ADVANCED_ALLOWALLVIDEOTRANSMISSION 32946
#define ID_ADVANCED_ALLOWALLDESKTOPTRANSMISSION 32947
#define ID_ADVANCED_ALLOWALLMEDIAFILETRANSMISSION 32948
#define ID_CHANNELINFO_SPEAKCHANNELSTATE 32949
#define ID_POPUP_MESSAGES               32950
#define ID_KICK_KICKANDBANFROMCHANNEL   32951
#define ID_CHANNELS_BANNEDUSERSINCHANNEL 32952
#define ID_CLIENT_NEWCLIENTINSTANCE     32953
#define ID_POPUP_STOREFORMOVE           32954
#define TT_MAX_ID                       0xFFFF

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        552
#define _APS_NEXT_COMMAND_VALUE         32955
#define _APS_NEXT_CONTROL_VALUE         1597
#define _APS_NEXT_SYMED_VALUE           413
#endif
#endif
