set (TTCLASSIC_SOURCES
  explorer1.cpp
  gui/AboutBox.cpp
  gui/AbuseTab.cpp
  gui/AdvancedPage.cpp
  gui/BannedDlg.cpp
  gui/BanTypeDlg.cpp
  gui/BitmapSlider.cpp
  gui/ChangeStatusDlg.cpp
  gui/ChannelDlg.cpp
  gui/ChannelOpTab.cpp
  gui/ChatRichEditCtrl.cpp
  gui/ChatTab.cpp
  gui/ClientPage.cpp
  gui/CodecLimitTab.cpp
  gui/ConnectDlg.cpp
  gui/DesktopShareDlg.cpp
  gui/dialogex/ControlsEx.cpp
  gui/dialogex/DialogEx.cpp
  gui/DirectConDlg.cpp
  gui/ExListBox.cpp
  gui/FilesListCtrl.cpp
  gui/FilesTab.cpp
  gui/FileTransferDlg.cpp
  gui/GeneralPage.cpp
  gui/GenerateTTFileDlg.cpp
  gui/HostManagerDlg.cpp
  gui/InputDlg.cpp
  gui/IpAddressesDlg.cpp
  gui/KeyCompDlg.cpp
  gui/MediaStorageDlg.cpp
  gui/MessageDlg.cpp
  gui/MoveToChannelDlg.cpp
  gui/MyBitmapButton.cpp
  gui/MyEdit.cpp
  gui/MyPropertySheet.cpp
  gui/MySliderCtrl.cpp
  gui/MyTab.cpp
  gui/MyTabCtrl.cpp
  gui/OnlineUsersDlg.cpp
  gui/PositionUsersDlg.cpp
  gui/Resizer.cpp
  gui/RichEditThemed.cpp
  gui/RoomBox.cpp
  gui/SendLiveContentDlg.cpp
  gui/ServerPropertiesDlg.cpp
  gui/ServerStatisticsDlg.cpp
  gui/SessionTreeCtrl.cpp
  gui/SessionTreeCtrlWin32.cpp
  gui/ShortcutsPage.cpp
  gui/SoundEventsPage.cpp
  gui/SoundSysPage.cpp
  gui/splitterbar.cpp
  gui/StreamMediaDlg.cpp
  gui/SysColStatic.cpp
  gui/SystemTray.cpp
  gui/TextToSpeechPage.cpp
  gui/UserAccountsDlg.cpp
  gui/UserButton.cpp
  gui/UserDesktopDlg.cpp
  gui/UserInfoDlg.cpp
  gui/UserVideoDlg.cpp
  gui/UserVolumeDlg.cpp
  gui/VideoCapturePage.cpp
  gui/WebLoginDlg.cpp
  gui/WindowPage.cpp
  gui/XPTabCtrl.cpp
  Helper.cpp
  HttpRequest.cpp
  Languages.cpp
  PlaySoundThread.cpp
  settings/ClientXML.cpp
  settings/MyStd.cpp
  settings/Settings.cpp
  settings/XMLLanguages.cpp
  TeamTalkApp.cpp
  TeamTalkBase.cpp
  TeamTalkDlg.cpp
  wizard/BmpPalette.cpp
  wizard/DIBitmap.cpp
  wizard/NGWizard.cpp
  wizard/NGWizardPage.cpp
  wizard/ResizeCtrl.cpp
  wizard/WizCompletionPage.cpp
  wizard/WizGeneralPage.cpp
  wizard/WizMasterSheet.cpp
  wizard/WizSoundSysPage.cpp
  wizard/WizWelcomePage.cpp

  TeamTalk.rc
  
  res/bitmap1.bmp
  res/bmp00001.bmp
  res/bmp00002.bmp
  res/bmp00003.bmp
  res/bmp00004.bmp
  res/bmp00005.bmp
  res/bmp00006.bmp
  res/icon1.ico
  res/logo.bmp
  res/session.bmp
  res/session2.bmp
  res/TeamTalk.ico
  res/toolbar1.bmp
  res/toolbar2.bmp)

set (TTCLASSIC_HEADERS
  AppInfo.h
  explorer1.h
  gui/AboutBox.h
  gui/AbuseTab.h
  gui/AdvancedPage.h
  gui/BannedDlg.h
  gui/BanTypeDlg.h
  gui/BitmapSlider.h
  gui/ChangeStatusDlg.h
  gui/ChannelDlg.h
  gui/ChannelOpTab.h
  gui/ChatRichEditCtrl.h
  gui/ChatTab.h
  gui/ClientPage.h
  gui/CodecLimitTab.h
  gui/ConnectDlg.h
  gui/DesktopShareDlg.h
  gui/dialogex/ControlsEx.h
  gui/dialogex/DialogEx.h
  gui/DirectConDlg.h
  gui/ExListBox.h
  gui/FilesListCtrl.h
  gui/FilesTab.h
  gui/FileTransferDlg.h
  gui/GeneralPage.h
  gui/GenerateTTFileDlg.h
  gui/HostManagerDlg.h
  gui/InputDlg.h
  gui/IpAddressesDlg.h
  gui/KeyCompDlg.h
  gui/MediaStorageDlg.h
  gui/MessageDlg.h
  gui/MoveToChannelDlg.h
  gui/MyBitmapButton.h
  gui/MyEdit.h
  gui/MyPropertySheet.h
  gui/MySliderCtrl.h
  gui/MyTab.h
  gui/MyTabCtrl.h
  gui/OnlineUsersDlg.h
  gui/PositionUsersDlg.h
  gui/Resizer.h
  gui/RichEditThemed.h
  gui/RoomBox.h
  gui/SendLiveContentDlg.h
  gui/ServerPropertiesDlg.h
  gui/ServerStatisticsDlg.h
  gui/SessionTreeCtrl.h
  gui/SessionTreeCtrlWin32.h
  gui/ShortcutsPage.h
  gui/SoundEventsPage.h
  gui/SoundSysPage.h
  gui/splitterbar.h
  gui/StreamMediaDlg.h
  gui/SysColStatic.h
  gui/SystemTray.h
  gui/TextToSpeechPage.h
  gui/UserAccountsDlg.h
  gui/UserButton.h
  gui/UserDesktopDlg.h
  gui/UserInfoDlg.h
  gui/UserVideoDlg.h
  gui/UserVolumeDlg.h
  gui/VideoCapturePage.h
  gui/WebLoginDlg.h
  gui/WindowPage.h
  gui/XPTabCtrl.h
  Helper.h
  HttpRequest.h
  Languages.h
  License.h
  PlaySoundThread.h
  resource.h
  settings/ClientXML.h
  settings/MyStd.h
  settings/Settings.h
  settings/XMLLanguages.h
  stdafx.h
  TeamTalkApp.h
  TeamTalkBase.h
  TeamTalkDlg.h
  wizard/BmpPalette.h
  wizard/DIBitmap.h
  wizard/NGWizard.h
  wizard/NGWizardPage.h
  wizard/ResizeCtrl.h
  wizard/WizCompletionPage.h
  wizard/WizGeneralPage.h
  wizard/WizMasterSheet.h
  wizard/WizSoundSysPage.h
  wizard/WizWelcomePage.h)

set (TINYXML_SOURCES
  tinyxml/tinystr.cpp
  tinyxml/tinyxml.cpp
  tinyxml/tinyxmlerror.cpp
  tinyxml/tinyxmlparser.cpp)

set (TINYXML_HEADERS
  tinyxml/tinystr.h
  tinyxml/tinyxml.h)
    
